# Generated by Django 5.2.11 on 2026-02-09 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('nom_ar', models.CharField(max_length=255)),
                ('nom_fr', models.CharField(max_length=255)),
                ('nom_en', models.CharField(max_length=255)),
                ('nom_es', models.CharField(max_length=255)),
                ('nom_de', models.CharField(max_length=255)),
                ('description_ar', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True)),
                ('description_de', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='solutions/covers/')),
                ('demo_video', models.FileField(blank=True, max_length=255, null=True, upload_to='solutions/videos/')),
                ('avantage_ar', models.JSONField(blank=True, default=list)),
                ('avantage_fr', models.JSONField(blank=True, default=list)),
                ('avantage_en', models.JSONField(blank=True, default=list)),
                ('avantage_es', models.JSONField(blank=True, default=list)),
                ('avantage_de', models.JSONField(blank=True, default=list)),
                ('principale_fonctions_ar', models.JSONField(blank=True, default=list)),
                ('principale_fonctions_fr', models.JSONField(blank=True, default=list)),
                ('principale_fonctions_en', models.JSONField(blank=True, default=list)),
                ('principale_fonctions_es', models.JSONField(blank=True, default=list)),
                ('principale_fonctions_de', models.JSONField(blank=True, default=list)),
                ('use_cases_ar', models.JSONField(blank=True, default=list)),
                ('use_cases_fr', models.JSONField(blank=True, default=list)),
                ('use_cases_en', models.JSONField(blank=True, default=list)),
                ('use_cases_es', models.JSONField(blank=True, default=list)),
                ('use_cases_de', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
                'ordering': ['order', 'slug'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='solutions_s_is_acti_8dc03d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SolutionDemoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='solutions/demos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_images', to='solutions.solution')),
            ],
            options={
                'verbose_name': 'Image démo',
                'verbose_name_plural': 'Images démo',
                'ordering': ['order', 'id'],
            },
        ),
    ]
