# Generated by Django 5.2.11

from django.db import migrations


def copy_department_to_m2m(apps, schema_editor):
    """Recopie les anciennes affectations (Solution.department) vers Departement.solutions (M2M)."""
    Solution = apps.get_model('solutions', 'Solution')
    for solution in Solution.objects.filter(department__isnull=False).select_related('department'):
        solution.department.solutions.add(solution)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_solution_department'),
        ('departements', '0002_departement_solutions'),
    ]

    operations = [
        migrations.RunPython(copy_department_to_m2m, noop),
        migrations.RemoveField(
            model_name='solution',
            name='department',
        ),
    ]
