"""
Commande pour générer 10 solutions de démonstration.
Usage: python manage.py generate_solutions
"""
from django.core.management.base import BaseCommand
from django.utils.text import slugify
from solutions.models import Solution


SOLUTIONS_DATA = [
    {
        "nom_fr": "Assistant IA Conversationnel",
        "nom_en": "Conversational AI Assistant",
        "nom_ar": "مساعد الذكاء الاصطناعي المحادث",
        "nom_es": "Asistente de IA Conversacional",
        "nom_de": "Konversations-KI-Assistent",
        "description_fr": "Solution d'assistant virtuel pilotée par l'IA pour le support client, la qualification de leads et l'automatisation des réponses. Intégration CRM et personnalisation par secteur.",
        "description_en": "AI-powered virtual assistant for customer support, lead qualification and response automation. CRM integration and industry-specific customization.",
        "description_ar": "مساعد افتراضي مدعوم بالذكاء الاصطناعي لدعم العملاء وتأهيل العملاء المحتملين وأتمتة الردود.",
        "description_es": "Asistente virtual impulsado por IA para soporte al cliente, calificación de leads y automatización de respuestas.",
        "description_de": "KI-gesteuerter virtueller Assistent für Kundensupport, Lead-Qualifizierung und Antwortautomatisierung.",
        "avantage_fr": "Réduction du temps de réponse\nDisponibilité 24/7\nScalabilité illimitée\nTraçabilité des échanges",
        "avantage_en": "Faster response times\n24/7 availability\nUnlimited scalability\nConversation tracking",
        "principale_fonctions_fr": "Chatbot multilingue\nIntégration CRM\nAnalytics en temps réel\nScripts personnalisables",
        "principale_fonctions_en": "Multilingual chatbot\nCRM integration\nReal-time analytics\nCustom scripts",
        "use_cases_fr": "Support client\nQualification de leads\nFAQ automatisée\nPrise de rendez-vous",
        "use_cases_en": "Customer support\nLead qualification\nAutomated FAQ\nAppointment booking",
    },
    {
        "nom_fr": "Analyse Prédictive des Données",
        "nom_en": "Predictive Data Analytics",
        "nom_ar": "تحليلات البيانات التنبؤية",
        "nom_es": "Análisis Predictivo de Datos",
        "nom_de": "Prädiktive Datenanalyse",
        "description_fr": "Plateforme d'analyse prédictive et de machine learning pour anticiper les tendances, la demande et les risques. Tableaux de bord et API pour intégration métier.",
        "description_en": "Predictive analytics and machine learning platform to anticipate trends, demand and risks. Dashboards and API for business integration.",
        "description_ar": "منصة تحليلات تنبؤية وتعلم آلي للتنبؤ بالاتجاهات والطلب والمخاطر.",
        "description_es": "Plataforma de análisis predictivo y aprendizaje automático para anticipar tendencias, demanda y riesgos.",
        "description_de": "Prädiktive Analyse- und Machine-Learning-Plattform zur Antizipation von Trends, Nachfrage und Risiken.",
        "avantage_fr": "Précision des prévisions\nRéduction des coûts\nDécisions data-driven\nDétection d'anomalies",
        "avantage_en": "Forecast accuracy\nCost reduction\nData-driven decisions\nAnomaly detection",
        "principale_fonctions_fr": "Modèles ML personnalisés\nVisualisations\nAlertes automatiques\nExport des rapports",
        "principale_fonctions_en": "Custom ML models\nVisualizations\nAutomatic alerts\nReport export",
        "use_cases_fr": "Prévision de ventes\nMaintenance prédictive\nFraude\nRétention client",
        "use_cases_en": "Sales forecasting\nPredictive maintenance\nFraud detection\nCustomer retention",
    },
    {
        "nom_fr": "Reconnaissance et Traitement de Documents",
        "nom_en": "Document Recognition & Processing",
        "nom_ar": "التعرف على المستندات ومعالجتها",
        "nom_es": "Reconocimiento y Procesamiento de Documentos",
        "nom_de": "Dokumentenerkennung und -verarbeitung",
        "description_fr": "Extraction et structuration automatique des données à partir de factures, contrats, formulaires et documents scannés. OCR avancé et validation des champs.",
        "description_en": "Automatic extraction and structuring of data from invoices, contracts, forms and scanned documents. Advanced OCR and field validation.",
        "description_ar": "استخراج وهيكلة تلقائية للبيانات من الفواتير والعقود والنماذج والمستندات الممسوحة ضوئياً.",
        "description_es": "Extracción y estructuración automática de datos de facturas, contratos, formularios y documentos escaneados.",
        "description_de": "Automatische Extraktion und Strukturierung von Daten aus Rechnungen, Verträgen, Formularen und gescannten Dokumenten.",
        "avantage_fr": "Gain de temps massif\nMoins d'erreurs\nConformité archivage\nRecherche full-text",
        "avantage_en": "Massive time savings\nFewer errors\nArchive compliance\nFull-text search",
        "principale_fonctions_fr": "OCR multilingue\nModèles par type de doc\nWorkflow de validation\nExport JSON/CSV",
        "principale_fonctions_en": "Multilingual OCR\nDocument-type models\nValidation workflow\nJSON/CSV export",
        "use_cases_fr": "Factures fournisseurs\nContrats\nFormulaires clients\nArchives légales",
        "use_cases_en": "Supplier invoices\nContracts\nCustomer forms\nLegal archives",
    },
    {
        "nom_fr": "Recommandation Personnalisée",
        "nom_en": "Personalized Recommendation",
        "nom_ar": "التوصيات الشخصية",
        "nom_es": "Recomendación Personalizada",
        "nom_de": "Personalisierte Empfehlung",
        "description_fr": "Moteur de recommandation (produits, contenus, offres) basé sur le comportement utilisateur et le contexte. A/B testing et métriques d'engagement intégrés.",
        "description_en": "Recommendation engine (products, content, offers) based on user behavior and context. Built-in A/B testing and engagement metrics.",
        "description_ar": "محرك توصيات (منتجات، محتوى، عروض) يعتمد على سلوك المستخدم والسياق.",
        "description_es": "Motor de recomendación (productos, contenido, ofertas) basado en el comportamiento del usuario y el contexto.",
        "description_de": "Empfehlungsmotor (Produkte, Inhalte, Angebote) basierend auf Nutzerverhalten und Kontext.",
        "avantage_fr": "Augmentation du panier moyen\nMeilleure rétention\nExpérience personnalisée\nROI mesurable",
        "avantage_en": "Higher average basket\nBetter retention\nPersonalized experience\nMeasurable ROI",
        "principale_fonctions_fr": "Modèles collaboratif / contenu\nFiltrage en temps réel\nExplicabilité\nDashboard performance",
        "principale_fonctions_en": "Collaborative / content models\nReal-time filtering\nExplainability\nPerformance dashboard",
        "use_cases_fr": "E-commerce\nStreaming\nNewsletters\nFormation en ligne",
        "use_cases_en": "E-commerce\nStreaming\nNewsletters\nOnline training",
    },
    {
        "nom_fr": "Modération de Contenu Automatisée",
        "nom_en": "Automated Content Moderation",
        "nom_ar": "الاعتدال التلقائي للمحتوى",
        "nom_es": "Moderación de Contenido Automatizada",
        "nom_de": "Automatisierte Inhaltsmoderation",
        "description_fr": "Détection et filtrage automatique de contenus inappropriés (texte, image, vidéo). Politiques personnalisables et revue humaine intégrée pour les cas limites.",
        "description_en": "Automatic detection and filtering of inappropriate content (text, image, video). Customizable policies and integrated human review for edge cases.",
        "description_ar": "اكتشاف وتصفية تلقائية للمحتوى غير المناسب (نص، صورة، فيديو).",
        "description_es": "Detección y filtrado automático de contenido inapropiado (texto, imagen, vídeo).",
        "description_de": "Automatische Erkennung und Filterung unangemessener Inhalte (Text, Bild, Video).",
        "avantage_fr": "Conformité légale\nProtection de la marque\nRéactivité\nAudit trail",
        "avantage_en": "Legal compliance\nBrand protection\nResponsiveness\nAudit trail",
        "principale_fonctions_fr": "NLP + vision\nRègles métier\nFile d'attente modérateurs\nRapports",
        "principale_fonctions_en": "NLP + vision\nBusiness rules\nModerator queue\nReports",
        "use_cases_fr": "Réseaux sociaux\nMarketplaces\nForums\nChats internes",
        "use_cases_en": "Social networks\nMarketplaces\nForums\nInternal chats",
    },
    {
        "nom_fr": "Résumé et Synthèse de Texte",
        "nom_en": "Text Summarization & Synthesis",
        "nom_ar": "تلخيص وتركيب النص",
        "nom_es": "Resumen y Síntesis de Texto",
        "nom_de": "Textzusammenfassung und -synthese",
        "description_fr": "Résumés automatiques (extractif et abstractif), synthèse de rapports et génération de comptes-rendus. Adapté aux documents longs et multilingues.",
        "description_en": "Automatic summaries (extractive and abstractive), report synthesis and meeting minutes generation. Suited for long and multilingual documents.",
        "description_ar": "ملخصات تلقائية (استخراجية وتجريدية) وتركيب التقارير وإنشاء محاضر الاجتماعات.",
        "description_es": "Resúmenes automáticos (extractivos y abstractos), síntesis de informes y generación de actas.",
        "description_de": "Automatische Zusammenfassungen (extraktiv und abstraktiv), Berichtssynthese und Protokollerstellung.",
        "avantage_fr": "Gain de temps lecture\nPoints clés identifiés\nPlusieurs longueurs\nMulti-langue",
        "avantage_en": "Reading time saved\nKey points identified\nMultiple lengths\nMultilingual",
        "principale_fonctions_fr": "Résumé court / long\nBullet points\nCR de réunion\nAPI batch",
        "principale_fonctions_en": "Short / long summary\nBullet points\nMeeting minutes\nBatch API",
        "use_cases_fr": "Veille juridique\nRapports annuels\nRéunions\nPresse",
        "use_cases_en": "Legal watch\nAnnual reports\nMeetings\nPress",
    },
    {
        "nom_fr": "Recherche Sémantique et RAG",
        "nom_en": "Semantic Search & RAG",
        "nom_ar": "البحث الدلالي و RAG",
        "nom_es": "Búsqueda Semántica y RAG",
        "nom_de": "Semantische Suche und RAG",
        "description_fr": "Recherche par sens et par contexte (RAG) sur vos bases documentaires. Réponses précises avec citation des sources. Idéal pour knowledge base et support.",
        "description_en": "Search by meaning and context (RAG) over your document bases. Accurate answers with source citation. Ideal for knowledge base and support.",
        "description_ar": "بحث بالمعنى والسياق (RAG) على قواعد المستندات. إجابات دقيقة مع الاستشهاد بالمصادر.",
        "description_es": "Búsqueda por significado y contexto (RAG) sobre sus bases documentales. Respuestas precisas con cita de fuentes.",
        "description_de": "Suche nach Bedeutung und Kontext (RAG) in Ihren Dokumentenbasen. Präzise Antworten mit Quellenangabe.",
        "avantage_fr": "Pertinence des réponses\nSources traçables\nÀ jour avec vos docs\nPas de hallucination",
        "avantage_en": "Answer relevance\nTraceable sources\nUp to date with your docs\nNo hallucination",
        "principale_fonctions_fr": "Embeddings personnalisés\nChunking intelligent\nReranking\nInterface admin",
        "principale_fonctions_en": "Custom embeddings\nSmart chunking\nReranking\nAdmin interface",
        "use_cases_fr": "Base de connaissances\nSupport technique\nDocumentation\nConformité",
        "use_cases_en": "Knowledge base\nTechnical support\nDocumentation\nCompliance",
    },
    {
        "nom_fr": "Traduction et Localisation IA",
        "nom_en": "AI Translation & Localization",
        "nom_ar": "الترجمة والتدويل بالذكاء الاصطناعي",
        "nom_es": "Traducción y Localización con IA",
        "nom_de": "KI-Übersetzung und -Lokalisierung",
        "description_fr": "Traduction automatique de qualité et localisation (ton, termes métier, SEO) pour sites, apps et contenus. Glossaires et mémoire de traduction.",
        "description_en": "Quality machine translation and localization (tone, domain terms, SEO) for websites, apps and content. Glossaries and translation memory.",
        "description_ar": "ترجمة آلية عالية الجودة وتدويل (نبرة، مصطلحات المجال، تحسين محركات البحث) للمواقع والتطبيقات والمحتوى.",
        "description_es": "Traducción automática de calidad y localización (tono, términos de dominio, SEO) para sitios, apps y contenido.",
        "description_de": "Qualitäts-Maschinübersetzung und Lokalisierung (Ton, Fachbegriffe, SEO) für Websites, Apps und Inhalte.",
        "avantage_fr": "Cohérence terminologique\nDélais raccourcis\nCoûts maîtrisés\nSEO multilingue",
        "avantage_en": "Terminology consistency\nShorter lead times\nControlled costs\nMultilingual SEO",
        "principale_fonctions_fr": "Modèles par domaine\nGlossaires\nPost-édition option\nAPI",
        "principale_fonctions_en": "Domain-specific models\nGlossaries\nOptional post-editing\nAPI",
        "use_cases_fr": "Sites web\nApplications\nCatalogues\nContrats",
        "use_cases_en": "Websites\nApplications\nCatalogs\nContracts",
    },
    {
        "nom_fr": "Détection d'Anomalies et Monitoring",
        "nom_en": "Anomaly Detection & Monitoring",
        "nom_ar": "اكتشاف الشذوذ والمراقبة",
        "nom_es": "Detección de Anomalías y Monitoreo",
        "nom_de": "Anomalieerkennung und Monitoring",
        "description_fr": "Surveillance en temps réel des métriques (IT, production, business) avec détection d'anomalies et alertes. Réduction des faux positifs par apprentissage.",
        "description_en": "Real-time monitoring of metrics (IT, production, business) with anomaly detection and alerts. Reduced false positives through learning.",
        "description_ar": "مراقبة في الوقت الفعلي للمقاييس (IT، الإنتاج، الأعمال) مع اكتشاف الشذوذ والتنبيهات.",
        "description_es": "Monitoreo en tiempo real de métricas (IT, producción, negocio) con detección de anomalías y alertas.",
        "description_de": "Echtzeit-Überwachung von Metriken (IT, Produktion, Business) mit Anomalieerkennung und Alarmen.",
        "avantage_fr": "Détection précoce\nMoins de faux positifs\nTableaux de bord\nIntégration SI",
        "avantage_en": "Early detection\nFewer false positives\nDashboards\nSI integration",
        "principale_fonctions_fr": "Seuils adaptatifs\nSéries temporelles\nAlertes multi-canal\nHistorique",
        "principale_fonctions_en": "Adaptive thresholds\nTime series\nMulti-channel alerts\nHistory",
        "use_cases_fr": "Infrastructure IT\nChaîne de production\nKPI business\nSécurité",
        "use_cases_en": "IT infrastructure\nProduction line\nBusiness KPIs\nSecurity",
    },
    {
        "nom_fr": "Génération de Contenu Assistée",
        "nom_en": "Assisted Content Generation",
        "nom_ar": "توليد المحتوى بمساعدة الذكاء الاصطناعي",
        "nom_es": "Generación de Contenido Asistida",
        "nom_de": "Assistierte Inhaltserstellung",
        "description_fr": "Génération de textes (articles, posts, emails, fiches produit) avec contrôle du ton et de la structure. Intégration CMS et workflow de validation.",
        "description_en": "Generation of texts (articles, posts, emails, product sheets) with control over tone and structure. CMS integration and validation workflow.",
        "description_ar": "توليد نصوص (مقالات، منشورات، رسائل بريد إلكتروني، صحائف منتجات) مع التحكم في النبرة والهيكل.",
        "description_es": "Generación de textos (artículos, publicaciones, correos, fichas de producto) con control del tono y la estructura.",
        "description_de": "Erstellung von Texten (Artikel, Posts, E-Mails, Produktblätter) mit Kontrolle über Ton und Struktur.",
        "avantage_fr": "Productivité rédaction\nCohérence de marque\nA/B testing contenu\nSEO intégré",
        "avantage_en": "Writing productivity\nBrand consistency\nContent A/B testing\nBuilt-in SEO",
        "principale_fonctions_fr": "Templates\nTon / style\nRéutilisation snippets\nPublication planifiée",
        "principale_fonctions_en": "Templates\nTone / style\nSnippet reuse\nScheduled publishing",
        "use_cases_fr": "Blog / SEO\nRéseaux sociaux\nNewsletters\nFiches produits",
        "use_cases_en": "Blog / SEO\nSocial media\nNewsletters\nProduct sheets",
    },
    {
        "nom_fr": "Orchestration de Workflows IA",
        "nom_en": "AI Workflow Orchestration",
        "nom_ar": "تنسيق سير عمل الذكاء الاصطناعي",
        "nom_es": "Orquestación de Flujos de Trabajo IA",
        "nom_de": "KI-Workflow-Orchestrierung",
        "description_fr": "Plateforme pour enchaîner modèles IA, règles métier et actions (API, BDD, notifications). Pipelines reproductibles, versionnés et monitorés.",
        "description_en": "Platform to chain AI models, business rules and actions (API, DB, notifications). Reproducible, versioned and monitored pipelines.",
        "description_ar": "منصة لربط نماذج الذكاء الاصطناعي وقواعد الأعمال والإجراءات (API، قاعدة البيانات، الإشعارات).",
        "description_es": "Plataforma para encadenar modelos de IA, reglas de negocio y acciones (API, BDD, notificaciones).",
        "description_de": "Plattform zur Verkettung von KI-Modellen, Geschäftsregeln und Aktionen (API, DB, Benachrichtigungen).",
        "avantage_fr": "Réutilisabilité\nTraçabilité\nScalabilité\nCoût maîtrisé",
        "avantage_en": "Reusability\nTraceability\nScalability\nControlled cost",
        "principale_fonctions_fr": "Éditeur visuel\nTriggers\nLogs et métriques\nRollback",
        "principale_fonctions_en": "Visual editor\nTriggers\nLogs and metrics\nRollback",
        "use_cases_fr": "Automatisation métier\nEnrichissement données\nValidation en chaîne\nReporting auto",
        "use_cases_en": "Business automation\nData enrichment\nChain validation\nAuto reporting",
    },
]


class Command(BaseCommand):
    help = "Génère 10 solutions de démonstration (multilingue FR, EN, AR, ES, DE)."

    def add_arguments(self, parser):
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Supprimer toutes les solutions existantes avant de créer les nouvelles.",
        )

    def handle(self, *args, **options):
        if options.get("clear"):
            count_before = Solution.objects.count()
            Solution.objects.all().delete()
            self.stdout.write(self.style.WARNING(f"Supprimé {count_before} solution(s)."))

        created = 0
        for order, data in enumerate(SOLUTIONS_DATA, start=1):
            slug = slugify(data["nom_fr"])[:100]
            if not slug:
                slug = f"solution-{order}"
            if Solution.objects.filter(slug=slug).exists():
                self.stdout.write(self.style.WARNING(f"Solution déjà existante: {slug}"))
                continue
            Solution.objects.create(
                slug=slug,
                order=order,
                nom_fr=data["nom_fr"],
                nom_en=data["nom_en"],
                nom_ar=data["nom_ar"],
                nom_es=data["nom_es"],
                nom_de=data["nom_de"],
                description_fr=data["description_fr"],
                description_en=data["description_en"],
                description_ar=data.get("description_ar", data["description_fr"]),
                description_es=data.get("description_es", data["description_fr"]),
                description_de=data.get("description_de", data["description_fr"]),
                avantage_fr=data["avantage_fr"],
                avantage_en=data["avantage_en"],
                avantage_ar=data.get("avantage_ar", data["avantage_fr"]),
                avantage_es=data.get("avantage_es", data["avantage_fr"]),
                avantage_de=data.get("avantage_de", data["avantage_fr"]),
                principale_fonctions_fr=data["principale_fonctions_fr"],
                principale_fonctions_en=data["principale_fonctions_en"],
                principale_fonctions_ar=data.get("principale_fonctions_ar", data["principale_fonctions_fr"]),
                principale_fonctions_es=data.get("principale_fonctions_es", data["principale_fonctions_fr"]),
                principale_fonctions_de=data.get("principale_fonctions_de", data["principale_fonctions_fr"]),
                use_cases_fr=data["use_cases_fr"],
                use_cases_en=data["use_cases_en"],
                use_cases_ar=data.get("use_cases_ar", data["use_cases_fr"]),
                use_cases_es=data.get("use_cases_es", data["use_cases_fr"]),
                use_cases_de=data.get("use_cases_de", data["use_cases_fr"]),
                is_active=True,
            )
            created += 1
            self.stdout.write(self.style.SUCCESS(f"Créé: {data['nom_fr']} ({slug})"))

        self.stdout.write(self.style.SUCCESS(f"\n{created} solution(s) créée(s)."))
