# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('nom_ar', models.CharField(max_length=255)),
                ('nom_fr', models.CharField(max_length=255)),
                ('nom_en', models.CharField(max_length=255)),
                ('nom_es', models.CharField(max_length=255)),
                ('nom_de', models.CharField(max_length=255)),
                ('description_ar', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True)),
                ('description_de', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='departements/covers/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['order', 'slug'],
            },
        ),
    ]
