# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
        ('departements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='solutions',
            field=models.ManyToManyField(
                blank=True,
                related_name='departements',
                to='solutions.solution',
            ),
        ),
    ]
